### ISSUE TITLE
Godot 4.0?

### ISSUE THREAD

**Issue by ImPI-314** [Iakobs/godot-google-play-game-services-android-plugin#1]
Hi, I'm starting using godot 4.0 leaving behind godot 3.X so I started looking for a google play service plugin to integrate in godot 4.0, do you think it can be possible with that one? I hope I'll get your answer soon, thank you!

**Comment by Iakobs** [comment]
Hi! The plan is to make this compatible with Godot 4 as well! I will let you know as soon as we make it 😊

Thanks for your interest!

**Comment by ImPI-314** [comment]
Great, I'll be in touch, tell me if you need some help, I can help with some code too.

**Comment by Iakobs** [comment]
Hi @ImPI-314 I've been making some tests with the Godot 4.0 android library and it seems to work more or less, but Godot 4.0 is definitely not ready for use with android yet and I can't test the plugin properly. I would suggest waiting until a stable release of Godot 4.1, what do you think?

**Comment by Miskler** [comment]
Hi! I'm wondering what problems Godot 4 has in terms of exporting for Android? I understand that in the current state, it was better for the 4th generation not to go out, but still I wonder what is broken there.

**Comment by Iakobs** [comment]
> Hi! I'm wondering what problems Godot 4 has in terms of exporting for Android? I understand that in the current state, it was better for the 4th generation not to go out, but still I wonder what is broken there.

Hi! Thanks for your interest! The problem was basically that the emulator wasn't able to properly draw the app, due to problems with the graphic backend, hence making the testing with the demo project impossible.

I was able to sign in to game services but that's all I could try. I guess I can make the app an automated integration test of sorts and just call to the library methods automatically instead of relying on manual input.

**Comment by ayremon** [comment]
Any news about the 4.x porting?

**Comment by Iakobs** [comment]
Hi, there are no news about this yet. Thanks for your interest.







---- El mié., 20 sept. 2023 16:42:50 +0200, pinghetto ***@***.***> escribió ----





Any news about the 4.x porting?

**Comment by hubbaba** [comment]
@pinghetto  If you're looking for a 4.1 compatible plugin, check out https://github.com/finepointcgi/PGSGP

**Comment by Iakobs** [comment]
Hi, @ImPI-314

The updated version of this plugin for godot 4.2 is ready in a [new repo](https://github.com/Iakobs/godot-play-game-services).

It only exposes the android interface to gdscript for now, so you will have to code yourself the gdscript code for your game. I'm working on making soon a gdscript wrapper for all of that.
