### ISSUE TITLE
Is, this pugin, able to save/load game data?

### ISSUE THREAD

**Issue by joined72** [Iakobs/godot-google-play-game-services-android-plugin#3]
As the title.

**Comment by Iakobs** [comment]
Hi @joined72 thanks a lot for your interest! Unfortunately the plugin has not covered that side of the google sdk yet. I will leave this open, as I plan to integrate more services and this one is definitely an important one!

**Comment by ayremon** [comment]
> Hi @joined72 thanks a lot for your interest! Unfortunately the plugin has not covered that side of the google sdk yet. I will leave this open, as I plan to integrate more services and this one is definitely an important one!

OK, thank you.

**Comment by Iakobs** [comment]
Hi again, @joined72 

I have created another repository for the Godot 4.2 version. If I add the cloud saves functionality, it will be there!

This is the [new repo](https://github.com/Iakobs/godot-play-game-services).

**Comment by Sajeg** [comment]
So no cloud saves on Godot 3.5?

**Comment by Iakobs** [comment]
Hi @Sajeg not for now, I'm afraid. I might add it in the future, but not the near one.

**Comment by Sajeg** [comment]
Alright thank you for the Quick response.

**Comment by Iakobs** [comment]
Hi @joined72 and @Sajeg 

The Save Games functionality is ready in the [new version of the plugin for gotdot 4.2](https://github.com/Iakobs/godot-play-game-services), in case you want to try it!

**Comment by Sajeg** [comment]
That's cool. I'll definitely check it out.

**Comment by ayremon** [comment]
> Hi @joined72 and @Sajeg
> 
> The Save Games functionality is ready in the [new version of the plugin for gotdot 4.2](https://github.com/Iakobs/godot-play-game-services), in case you want to try it!

Thanks a lot, can you tell me the difference from Google Play Service 1 vs 2?

**Comment by Iakobs** [comment]
> Thanks a lot, can you tell me the difference from Google Play Service 1 vs 2?

Hi @joined72 It's basically a change coming from Google. The v1 of the play game services library is older and uses different mechanisms and APIs to provide the services. Version 2 is a more modern and easy to implement approach.

**Comment by joelgomes1994** [comment]
@Iakobs @Sajeg I'm working on the port of the latest 4.x features to 3.x on [this fork](https://github.com/joelgomes1994/godot-google-play-game-services-android-plugin/tree/feature-parity-3.5), I'll create a pull request as soon as I finish and test everything on my project. I'll update the 3.x [GDScript addon](https://github.com/joelgomes1994/godot-google-play-game-services-plugin) as well.

**Comment by Sajeg** [comment]
That sounds awesome. I also wanted to try and port it, but it seems that I don't have to do it anymore.

**Comment by Iakobs** [comment]
Wow, @joelgomes1994 that's freakin awesome! thanks a lot for your help! I was about to abandon this plugin since the one for godot 4.2 has given me so much work, so it's great to see someone's still interested!

**Comment by joelgomes1994** [comment]
Implemented and merged in the `main` branch from #4. Release available at [releases](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/releases), GDScript reference available at [REFERENCE.md](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/blob/main/REFERENCE.md) and GDScript addon wrapper available at [this repository](https://github.com/Iakobs/godot-google-play-game-services-plugin).
