### ISSUE TITLE
Crashes on events/leaderboards without icons

### ISSUE THREAD

**Issue by yancouto** [Iakobs/godot-google-play-game-services-android-plugin#7]
The plugin crashes when you try to load an event or leaderboard that has no icon, with a null pointer exception. I verified that adding an icon (I actually had to create another leaderboard with icon) did make it start working again.

(Otherwise a great plugin, thank you!)

**Comment by yancouto** [comment]
For events I'm actually still getting the null pointer exception (on the icon) even when I added the icon.

**Comment by Iakobs** [comment]
Hi @yancouto ! thanks a lot for letting me know, I will try to add a fix as soon as possible, I'll keep you posted!

**Comment by Iakobs** [comment]
Hi @yancouto you have a [new release ](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/releases/tag/v2.0.3) with the fix available! Please let me know if this fixes the issue!

**Comment by yancouto** [comment]
That was super fast!! And it seems to be working. Thanks a lot!
