### ISSUE TITLE
Any plans to add more leaderboard methods?

### ISSUE THREAD

**Issue by attilaoroszdev** [Iakobs/godot-google-play-game-services-android-plugin#8]
Hey,

Great plugin, amazing work, so first of all, thank you!

To the question:

I was wondering if you had any plans for adding some more leaderboard specific stuff from the official SDK, stuff like `loadTopScores()` and `loadPlayerCenteredScores()`.

They would be quite useful for adding custom leaderboards to the game without having to display the native popup

Are there any limitations/problems around these? From the [docs](https://developers.google.com/android/reference/com/google/android/gms/games/LeaderboardsClient), it looks like they work similarly to already implemented methods.

(I might try it myself, but I've never used Kotlin, so it will probably take a while, and the code quality might suffer a bit, too) :D

Thanks again for the great work.

**Comment by Iakobs** [comment]
hi @attilaoroszdev thanks a lot! I'm glad you're finding the plugin useful!

I have another version of the plugin for Godot 4 with those methods implemented, so backporting them should be fairly simple, I will try to do it this weekend!

**Comment by attilaoroszdev** [comment]
Nice one, that would save me a lot of pain. :) Thanks a lot.

**Comment by attilaoroszdev** [comment]
@Iakobs, Had a look at the other repo, and did it quickly myself, because I needed it today. (Without it, it would have been a pain, but at least with your existing code I didn't have to learn Kotlin from scratch. :laughing:) Opened a PR just now, it might save you some work.

**Comment by Iakobs** [comment]
Incredible! thanks a lot, I'm reviewing the pr!

**Comment by Iakobs** [comment]
I already merged the pr but I don't have the computer at hand right now to make the release, although I understand that you already have the binaries, etc right?

**Comment by attilaoroszdev** [comment]
Yeah, had to try with live data, if it really worked, so I exported/imported the `aar` already, so no rush. :)

**Comment by attilaoroszdev** [comment]
Just a little heads up, it turns out my efforts were somewhat futile. Currently Google Play Games seems to default to not set the player's account to public (more [here](https://www.reddit.com/r/androiddev/comments/17j00ci/google_play_games_defaults_user_privacy_settings/)) with no easy way to access the Settings if you are not displaying the native popup (see [here](https://issuetracker.google.com/issues/308253248)).

So currently, custom leaderboards are severely limited at the moment.  I wonder why it is, but any time I deal with Google SDKs, it feels like they are trying to be as much of a pain in the ~~expletive redacted~~ as they possibly can... Sad. :disappointed:

**Comment by Iakobs** [comment]
Oh, wow. That's disappointing, yes, Google is always a pain. 

Anyways, I published the latest version [here](https://github.com/Iakobs/godot-google-play-game-services-android-plugin/releases/tag/v2.1.0). I will close this issue now, but let me know if you need something else! Thanks a lot for your help!
